Includehttps
jgomezselles/hermes pull request #50
Opened 2021-08-26 16:05 UTC by PepeluDev

Hi @jgomezselles,

I have been using Hermes as traffic generator for a while and I thought that it would be awesome if it could use H2 and not only H2C. That is why I am creating this pull request.

This two changes make Hermes able to talk to HTTPS endpoints. Although it works, I am still working on the UTs for the HTTPS connection (managing self-signed certs and so) but I thought that it would be easier to start the conversation now. I will keep working on it and will make another pull request (or make a fix to the last commit, as you wish) once is done.

Cheers!

2021-09-01 19:58 UTC, jgomezselles commented
Hi @PepeluDev 
Thanks a lot for the PR. It is indeed a very good (and needed) enhancement. While you finish the tests and, as requested, I'm starting a review. It's the first time I do it in github so I hope it goes well. Any feedback is welcome!

2021-09-01 20:18 UTC, jgomezselles requested changes
Please, take a look at the comments.

- [x] I am proposing a way of not needing the shared_ptr
- [ ] Some bool parameters should be const
- [ ] Please, remember to run the format
- [ ] I think you'll need to change the manipulate function to get the tests working
- [ ] Waiting for those tests!

Anyhow, thanks a lot for implementing this. I really appreciate it.

2021-09-01 20:18 UTC, jgomezselles commented on src/http2_client/client_impl.hpp
> +                const std::string& p, bool secure_session = false);
```suggestion
                const std::string& p, const bool secure_session = false);
```

2021-09-01 20:18 UTC, jgomezselles commented on src/script/script_reader.cpp
> +    }
Minor: if you want, you could use:
```suggestion
    server.secure = is_present("/secure") ? get_value<bool>("/secure") : false;
```

2021-09-02 16:19 UTC, PepeluDev commented
Hi again @jgomezselles thanks a lot for your review, I agree with all the changes. I will update the code asap and try to submit another revision, I still don't know how to fix commits in a PR, it's also my first PR. I will also update you with the UTs asap :)

2021-09-04 09:50 UTC, PepeluDev commented
Hi @jgomezselles I have added 4 commits with the changes that you requested. Please take the time to review em whenever you are able and do not hesitate to ask for more! Now I will continue with the tests.
Cheers!!

2021-09-05 21:39 UTC, PepeluDev commented
Hi again @jgomezselles, tests for secure connections are finally here. 

As a summary, to be able to launch a secure server that can be trusted by the client transparently, it is needed to have a trusted CA that can sign the server's certificate. The script "generateCryptographicMaterial" can do all the work, it generates the CA, updates the development container with the CA cert and generates the server's cryptographic material.

I took the freedom to modify a little bit the Dockerfiles, including the stuff that the script needs. I also included the command to run the tests when creating the final image, excluding the test "stats_test_extended.PrintAndWrite", which wasn't passing. Another consideration that you may take into account is that the step for downloading boost in the base image Dockerfile is not working anymore, I think they have changed the library location, see more [here](https://www.boost.org/users/download/).

2021-09-11 21:39 UTC, jgomezselles commented
As discussed offline, I'm merging it (though it will break the CI). After that, I will make changes in a separate PR.
Thanks a lot for the contribution! :)

2021-09-11 21:39 UTC, merged

2021-09-11 21:52 UTC, PepeluDev commented
Perfect then! I am happy to contribute to Hermes, it helped me a lot testing my services. I will keep an eye on the repo and will show it to my coworkers 😄