Fix Content-Type & Content-Length header keys
jgomezselles/hermes pull request #63
Opened 2022-01-05 12:31 UTC by PepeluDev

Hi @jgomezselles 

I have recently pulled the latest changes from the Hermes repo, and when using it to trigger a performance test over the services I maintain I found some errors in the execution. Investigation led me to discover this small bug. So here is a simple PR :)

We love Hermes, cheers!

2022-01-05 15:27 UTC, jgomezselles requested changes
Hi @PepeluDev 
Great to see you around again. Thanks for the contribution and sorry for the mistake.
As http2 (and 1) headers are not [case sensitive](https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive/5259004) I'm going to ask you to keep them lower-case, as they were before my [mistake](https://github.com/jgomezselles/hermes/commit/32851c914cd8eb158ab0c7a3e8e3dc860a33d8d2#diff-49dbeba9edb8f6b223f61c799bc2a097e695862beeb9349583800f2f1e6182efL99).

For the tests, I think this can be handled in good all unit test.

So I'm going to ask you to, please, add the following changes:
(if you are in a rush for this, I can merge it and open a separate issue. NP with that. Please, let me know if that's the case.)
- [ ] Change lines 17, 19 and 22 [here](https://github.com/jgomezselles/hermes/blob/main/ut/http2_client/client_utils_test.cpp#L17) for the corresponding hardcoded string "content-length", and so on.
- [ ] Keep the header keys as lowercase (sorry to be picky about this one, but I kind of feel that keeping them Camel-Case give the impression that this is case sensitive).

I've been checking the client unit tests and doing such check can be tricky. If you agree, with these two proposed changes I think we are all set.

Thanks a lot again!

2022-01-05 15:27 UTC, jgomezselles commented on src/http2_client/client_utils.hpp
> +inline static const std::string CONTENT_TYPE = "Content-Type";
Please, keep it lowercase

2022-01-05 15:27 UTC, jgomezselles commented on src/http2_client/client_utils.hpp
> +inline static const std::string CONTENT_LENGTH = "Content-Length";
Here too

2022-01-10 08:39 UTC, PepeluDev commented
Hi @jgomezselles you know it's always a pleasure to try to contribute something to Hermes :)

Thank you for your comments, yes, I understand that we can keep the header keys as "content-type" and "content-length".  I will update the PR asap, I'm also changing the tests file.

cheers!

2022-01-10 11:11 UTC, jgomezselles approved these changes
Thanks a lot!

2022-01-10 11:12 UTC, merged